### ISSUE TITLE
[Feature Request] Ability to switch autoAction during ddu launch

### ISSUE THREAD

**Issue by yuki-yano** [Shougo/ddu-ui-ff#103]
There are times when I want to disable the preview display while using ddu with a preview set in `autoAction`. Even if the preview is closed once, if it is set in `autoAction`, the preview will be redisplayed when moving the cursor.

I would like a function that can cancel the specified autoAction in that ddu session. Also, when this function is supported, it is desirable that the preview in `autoAction` is enabled again in the next launch of ddu, but should this be handled with something like autocmd?

**Comment by Shougo** [comment]
`toggleAutoAction` is added.
