### ISSUE TITLE
Filter window not updated properly for split='no'

### ISSUE THREAD

**Issue by KazMorita** [Shougo/ddu-ui-ff#104]
# Problems summary
`ddu-ui-ff` does not renew the filter window properly when `split='no'`. When I enter the first letter for filtering, the filter window shows the result of filtering. The filter window no longer accepts input because it is showing filtered result, which is not modifiable. This is also reproduced in `vim=v9.0.1676`. It works perfectly fine when `split='horizontal'` is set.

## Expected
The filter window should not show the filtered result. Even after the input of the first letter, it should retain the filtering window.

## Environment Information

- ddu-ui-ff version (SHA1):a5238c6fea598f7b8f76d1c2ce280a7b01753aa5

- denops.vim version (SHA1):62b1d22b3e60fcc9e570a531a5af1e4b2393c15a

- deno version(`deno -V` output): deno 1.34.3

- OS: arch linux

- neovim/Vim `:version` output:
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath^=~/.plugins/Shougo/ddu-commands.vim
set runtimepath^=~/.plugins/Shougo/ddu-filter-matcher_substring
set runtimepath^=~/.plugins/Shougo/ddu-source-file_old
set runtimepath^=~/.plugins/Shougo/ddu-ui-ff
set runtimepath^=~/.plugins/Shougo/ddu.vim
set runtimepath^=~/.plugins/vim-denops/denops.vim

call ddu#custom#patch_global({
\   'ui': 'ff',
\   'uiParams': {
\     'ff': {
\       'split': 'no',
\     },
\   },
\   'sourceOptions': {
\     '_': {
\       'matchers': ['matcher_substring'],
\     },
\   },
  \ })

nnoremap <SPACE>fo <Cmd>Ddu -name=find file_old<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer> i <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. press 'SPACE fo'
2. press 'i'
3. enter the first letter to filter and you will not be able to continue filtering.

**Comment by Shougo** [comment]
Fixed.
