### ISSUE TITLE
Filter does not work properly

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/ddu-ui-ff#105]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

The cursor blows up every time you type a letter.

## Expected

Cursor does not move

## Environment Information

All plugins are latest.

FYI: The cause commit is 367833a481c92a4078773582833038195676f04a

- deno version(`deno -V` output): deno 1.35.0

- OS: Ubuntu 22.04 (WSL2)

- neovim/Vim `:version` output: NVIM v0.10.0-dev-3750e5e

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/ddu.vim
set runtimepath+=/path/to/ddu-ui-ff
set runtimepath+=/path/to/ddu-source-file
set runtimepath+=/path/to/ddu-filter-matcher_substring

call ddu#custom#patch_global(#{
      \ ui: 'ff',
      \ sources: [#{name: 'file'}],
      \})

autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `call ddu#start({})`
2. Input `i` to open filter window.
3. When you type something at random, the cursor is blown up to the `ddu-default` window.

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.
