### ISSUE TITLE
Opening a file when auto preview and floating window are set prevents writing to the file.

### ISSUE THREAD

**Issue by nekowasabi** [Shougo/ddu-ui-ff#107]
# Problems summary
In the windows vim environment, if the auto preview function and the floating window setting are set at the same time, the file will not be writable when opened.

Note: The probability of this occurring is about 10% to 20%.

## Expected
Even with auto preview and floating window settings, the file should be writable when opened.

## Environment Information

- ddu-ui-ff version (SHA1): 3e0a5ca6a7b020661eddfe6cd4e717c4bd28d210

- denops.vim version (SHA1):ec0a360bec4ae0583585c4566d56b70b7b2e96a8

- deno version(`deno -V` output): 1.34.3

- OS: windows11

- Vim `:version` output: vim9.0 1-1576, install by chocolately

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

set runtimepath+=~/path/to/denops.vim
set runtimepath+=~/path/to/ddu.vim
set runtimepath+=~/path/to/ddu-ui-ff
set runtimepath+=~/path/to/ddu-kind-file
set runtimepath+=~/path/to/ddu-filter-matcher_substring
set runtimepath+=~/path/to/ddu-source-file

call ddu#custom#patch_global(#{
      \   ui: 'ff',
      \ })

call ddu#custom#patch_global(#{
      \   uiParams: #{
      \     ff: #{
      \         startFilter: v:true,
      \         split: 'floating',
      \         prompt: '> ' ,
      \         filterSplitDirection: 'floating',
      \         filterFloatingPosition: 'top',
      \         highlights: #{filterText: 'Statement', floating: "Normal", floatingBorder: "Special"},
      \         floatingBorder: 'single',
      \         autoAction: #{name: "preview"},
      \         startAutoAction: v:true,
      \         previewFloating: v:true,
      \         floatingTitle: '',
      \         previewSplit: 'vertical',
      \     }
      \   },
      \ })

call ddu#custom#patch_global(#{
    \   kindOptions: #{
    \     file: #{
    \       defaultAction: 'open',
    \     },
    \   }
    \ })

call ddu#custom#patch_global(#{
    \   sourceOptions: #{
    \     _: #{
    \       matchers: ['matcher_substring'],
    \     },
    \   }
    \ })

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  nnoremap <buffer><silent> q
  \ <Cmd>close<CR>
  nnorema <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
        \<Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction
```

## How to reproduce the problem from Vim startup (Required!)

1. boot windows gvim.
2. execute `cd ~/',  for moving to home directory. This is needed to open vimrc in ddu.
3. execute  `call ddu#start({'sources': [{'name': 'file'}]})` in command line.
4. wait displaying ddu's window by floating window feature.
5. type `vimrc` and wait for the candidates to narrow down
6. type `<CR>`  for opening vimrc file.
7. execute `:w<CR>` in command line.
8. Cause msg `E382`

## Screenshot (if possible)
The sample video uses bugreport.vim as an example, but the vimrc specified in the reproduction procedure above will also occur with a certain probability.

![ddu_screenshot](https://github.com/Shougo/ddu-ui-ff/assets/3657473/9bcbdf17-3e7a-49cb-be7c-2982c0698a34)

**Comment by Shougo** [comment]
Hm... something wrong.

**Comment by Shougo** [comment]
Please test the latest version of `ddu-ui-ff`.

**Comment by nekowasabi** [comment]
Thanks for the correction.
We checked the operation, but it did not work as intended (the same phenomenon as in the video is reproduced).

**Comment by Shougo** [comment]
Reproduced.  It seems another problem.

**Comment by Shougo** [comment]
It is the bug of `ddu-kind-file`.  I will fix it.

**Comment by Shougo** [comment]
Fixed.  Please update `ddu-kind-file`.

**Comment by nekowasabi** [comment]
@Shougo 
Thank you.

The file can now be written.
However, the buffer selected from ddu is now opened in filterWindow.
The vim environment and initial settings are the same as above.

![ddu_screenshot](https://github.com/Shougo/ddu-ui-ff/assets/3657473/bee3c802-e07a-4350-9909-879bc4423a9a)

**Comment by Shougo** [comment]
Reproduced.  It seems from ddu's recent changes.

**Comment by Shougo** [comment]
Fixed.

**Comment by nekowasabi** [comment]
We have found a similar phenomenon and report it.
When `kind` is `open` and the candidate that is narrowed down is not a file or buffer (ddu-source-line is used in the video),
The error message is different from the error you fixed.
The reproduction condition is to add `set runtimepath+=~/path/to/ddu-source-line` to the minimum configuration vimrc,
The only requirement is to change the ddu command to be executed to `call ddu#start({'sources': [{'name': 'line'}]})`.

![ddu_screenshot](https://github.com/Shougo/ddu-ui-ff/assets/3657473/7c033539-28ed-40a2-a8c5-56f91d5a4509)

**Comment by nekowasabi** [comment]
Issue move to https://github.com/Shougo/ddu-ui-ff/issues/108
