### ISSUE TITLE
Opening a file when auto preview and floating window are set prevents open buffer or file.

### ISSUE THREAD

**Issue by nekowasabi** [Shougo/ddu-ui-ff#108]
# Problems summary
When `kind` is `open` and the candidate that is narrowed down is not a file or buffer (ddu-source-line is used in the video),

## Expected
Can open buffer or file by using `kind` is `open`.
ex. Using ddu-source-line.

## Environment Information

- ddu-ui-ff version (SHA1): 919ca5f0d3eb5c30c5f5f35ea1627d8bdf592d5c

- denops.vim version (SHA1): fece0a2b24655e42a3fd10dbbf2962d39b381e90

- deno version(`deno -V` output): 1.34.3

- OS: windows11

- Vim `:version` output: vim9.0 1-1576, install by chocolately

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

set runtimepath+=~/path/to/denops.vim
set runtimepath+=~/path/to/ddu.vim
set runtimepath+=~/path/to/ddu-ui-ff
set runtimepath+=~/path/to/ddu-kind-file
set runtimepath+=~/path/to/ddu-filter-matcher_substring
set runtimepath+=~/path/to/ddu-source-line

call ddu#custom#patch_global(#{
      \   ui: 'ff',
      \ })

call ddu#custom#patch_global(#{
      \   uiParams: #{
      \     ff: #{
      \         startFilter: v:true,
      \         split: 'floating',
      \         prompt: '> ' ,
      \         filterSplitDirection: 'floating',
      \         filterFloatingPosition: 'top',
      \         highlights: #{filterText: 'Statement', floating: "Normal", floatingBorder: "Special"},
      \         floatingBorder: 'single',
      \         autoAction: #{name: "preview"},
      \         startAutoAction: v:true,
      \         previewFloating: v:true,
      \         floatingTitle: '',
      \         previewSplit: 'vertical',
      \     }
      \   },
      \ })

call ddu#custom#patch_global(#{
    \   kindOptions: #{
    \     line: #{
    \       defaultAction: 'open',
    \     },
    \   }
    \ })

call ddu#custom#patch_global(#{
    \   sourceOptions: #{
    \     _: #{
    \       matchers: ['matcher_substring'],
    \     },
    \   }
    \ })

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  nnoremap <buffer><silent> q
  \ <Cmd>close<CR>
  nnorema <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
        \<Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. boot windows gvim.
2. execute `cd ~/',  for moving to home directory. This is needed to open vimrc in ddu.
3. execute  `call ddu#start({'sources': [{'name': 'line'}]})` in command line.
4. wait displaying ddu's window by floating window feature.
5. type `utf-8` and wait for the candidates to narrow down
6. type `<CR>`  for opening vimrc file.
7. Cause msg `E605`

## Screenshot (if possible)
![ddu_screenshot](https://github.com/Shougo/ddu-ui-ff/assets/3657473/7c033539-28ed-40a2-a8c5-56f91d5a4509)

**Comment by Shougo** [comment]
Thanks.  I will look it later.

**Comment by Shougo** [comment]
Fixed.

**Comment by nekowasabi** [comment]
It works.
Thank you!!
