### ISSUE TITLE
TerminalPreviewer shows the preview in both of the preview window and ff window

### ISSUE THREAD

**Issue by kyoh86** [Shougo/ddu-ui-ff#111]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Using the kind it returns `TerminalPreviewer` as `Previewer`, "Preview" action is called, ui-ff shows the result in both of the preview window and the ff window.

## Expected

It only shows the result in the preview window.

## Environment Information

- ddu-ui-ff version (SHA1): `f499322`

- denops.vim version (SHA1): `22e7ae3`

- deno version(`deno -V` output): `deno 1.35.1`

- OS: Arch Linux on WSL2

- neovim/Vim `:version` output: 

```NVIM v0.10.0-dev-33e1a8c
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/path/to/denops.vim
set rtp+=~/path/to/ddu.vim
set rtp+=~/path/to/ddu-ui-ff
set rtp+=~/path/to/dummy

call ddu#custom#patch_global(#{
      \   ui: "ff",
      \   sources: [#{name: "dummy"}],
      \ })
```

And prepare a dummy source & dummy kind

`~/path/to/dummy/denops/@ddu-sources/dummy.ts`

```ts
import type { GatherArguments } from "https://deno.land/x/ddu_vim@v3.4.3/base/source.ts";
import { BaseSource, Item } from "https://deno.land/x/ddu_vim@v3.4.3/types.ts";

type Params = Record<never,never>;
type ActionData = Record<never,never>;

export class Source extends BaseSource<Params, ActionData> {
  override kind = "dummy";

  override gather({ denops, sourceParams }: GatherArguments<Params>) {
    return new ReadableStream<Item<ActionData>[]>({
      async start(controller) {
        controller.enqueue([{
          word: "foo",
        }])
        controller.close()
      },
    });
  }

  override params(): Params {
    return {};
  }
}
```

`~/path/to/dummy/denops/@ddu-kinds/dummy.ts`

```ts
import {
  BaseKind,
  Previewer,
} from "https://deno.land/x/ddu_vim@v3.4.3/types.ts";

type Params = Record<never, never>;

export class Kind extends BaseKind<Params> {
  override actions = {};

  getPreviewer(): Promise<Previewer | undefined> {
    return Promise.resolve({
      kind: "terminal",
      cmds: ["echo", "bar"],
    });
  }

  params(): Params {
    return {};
  }
}
```
## How to reproduce the problem from neovim/Vim startup (Required!)

1. `:call ddu#start()`
2. `:call ddu#ui#do_action("preview")`

## Screenshot (if possible)
![image](https://github.com/Shougo/ddu-ui-ff/assets/5582459/f0fea086-a4f2-49f2-9dcc-69d0310268ff)

**Comment by Shougo** [comment]
Fixed.

**Comment by kyoh86** [comment]
Thanks! I have checked it is fixed!
