### ISSUE TITLE
after fireing action with chooseAction, the mode is INSERT not NORMAL

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#121]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
after firering action with chooseAction, the mode is NORMAL.

## Environment Information

- ddu-ui-ff version (SHA1):
c45fd23

- denops.vim version (SHA1):
9f1b8cf

- deno version(`deno -V` output):
deno 1.35.3

- OS:
WSL2 Ubuntu22.04

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-836+g6d93bdd45

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-action
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\	'ff': {
			\		'startFilter': v:true,
			\	}
			\ },
			\ 'sources': [
			\	{'name': 'file'},
			\ ],
			\ 'kindOptions': {
			\	'action': {
			\		'defaultAction': 'do'
			\	}
			\ },
			\ })<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	nnoremap <buffer> <CR>
				\ <Cmd>call ddu#ui#do_action('itemAction')<CR>
	nnoremap <buffer> a
				\ <Cmd>call ddu#ui#do_action('chooseAction')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()

function! s:ddu_filter_my_settings() abort
	inoremap <buffer> <C-l>
				\ <ESC><Cmd>call ddu#ui#ff#do_action('leaveFilterWindow')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f` to start ddu
2. type `<C-l>` in filter window to leave filter window.
3. type `a` in ddu window for fire `chooseAction`
4. type `<CR>` in ddu window with action source ( for example 'open' action )
5. after `open` action, the mode is INSERT...

## Screenshot (if possible)
![hoge](https://github.com/Shougo/ddu-ui-ff/assets/50443168/3d1072fa-0320-4e2f-b0b4-91bf1fdd1523)

**Comment by Shougo** [comment]
Fixed.  Please update `ddu-source-action`.
