### ISSUE TITLE
`filterFloatingTitle` is not setted after `updateOptions`

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#122]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
After `updateOptions`, filterFloatingTitle is setted.

## Environment Information

- ddu-ui-ff version (SHA1):
5d789ca
- denops.vim version (SHA1):
9f1b8cf
- deno version(`deno -V` output):
deno 1.35.3
- OS:
WSL2 Ubuntu22.04
- neovim/Vim `:version` output:
NVIM v0.10.0-dev-886+gb263c73b0
## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\	'ff': {
                        \               'startFilter': v:true,
			\		'split': 'floating',
			\		'floatingBorder': 'rounded'
			\	}
			\ },
			\ })<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	nnoremap <buffer><silent> u
				\ <Cmd>call ddu#ui#ff#do_action('updateOptions', #{
				\	uiParams: #{ 
				\		ff: #{
				\			floatingTitle: 'TitleOK',
				\			filterFloatingTitle: 'FilterNG'
				\		}
				\	}
				\ })<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()

function! s:ddu_filter_my_settings() abort
	inoremap <buffer> <C-l>
				\ <ESC><Cmd>call ddu#ui#ff#do_action('leaveFilterWindow')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f` to start ddu
2. type `<C-l>` to leave filter window
3. type `u` in ddu window to fire `updateOptions` action
4. then ddu window title is updated, but filter window title is not setted...

## Screenshot (if possible)
![hoge](https://github.com/Shougo/ddu-ui-ff/assets/50443168/7a37e4c2-d939-4e2f-ba69-54e5273ce636)
## Upload the log

 messages by `:redir` and `:message` (if errored)

**Comment by Shougo** [comment]
Fixed.  Please update ddu.vim.
