### ISSUE TITLE
`input()` does not work in custom action when `startFilter` is true.

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#123]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
`input()` work as well as `startFilter` is false.

## Environment Information

- ddu-ui-ff version (SHA1):
00ad412

- denops.vim version (SHA1):
68f607d

- deno version(`deno -V` output):
deno 1.33.2

- OS:
WSL2 Ubuntu22.04

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1052+g82150ca51-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.1693350652

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

function s:unko(args)
	let hoge = input('piyo: ')
	return 0
endfunction

call ddu#custom#action('kind', 'file', 'unko', function('s:unko'))

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': { 'ff': { 'startFilter': v:true } },
			\ 'sources': [{'name': 'file', 'params': {}}],
			\ })<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	nnoremap <buffer> u
				\ <ESC><Cmd>call ddu#ui#do_action('itemAction', {'name': 'unko'})<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()

function! s:ddu_filter_my_settings() abort
	inoremap <buffer> <C-l>
				\ <ESC><Cmd>call ddu#ui#ff#do_action('leaveFilterWindow')<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f` to start ddu
2. type `<C-l>` to leave filter window
3. type `u` to fire custom action
4. `input()` doesn't seem to work

## Screenshot (if possible)
`startFilter` is true
![startFilter](https://github.com/Shougo/ddu-ui-ff/assets/50443168/0df02274-4d28-4b69-889e-de86c4390a5c)

`startFilter` is false
![notStartFilter](https://github.com/Shougo/ddu-ui-ff/assets/50443168/a60b66c1-c385-4ffc-bdd4-42b028b80b2d)

**Comment by Shougo** [comment]
Fixed.
