### ISSUE TITLE
when fire the action via chooseAction with `startFilter=true` options, the mode will be INSERT.

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#129]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
the mode after firing the action is expected to be INESRT.

## Environment Information

- ddu-ui-ff version (SHA1):
ab39554
- denops.vim version (SHA1):
83f167b
- deno version(`deno -V` output):
deno 1.38.5
- OS:
WSL Ubuntu22.04.3
- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1846+gf31f260f0
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-action
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

let s:ddu_config_json =<< trim MARK
	{
		"ui": "ff",
		"uiParams": {
			"ff": {
				"startFilter": true
			}
		},
		"kindOptions": {
			"action": {
				"defaultAction": "do"
			}
		}
	}
MARK

let s:ddu_config_json = s:ddu_config_json->join('')->json_decode()

call ddu#custom#patch_global(s:ddu_config_json)

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [{'name': 'file', 'params': {}}],
			\ })<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	nnoremap <buffer> <CR>
				\ <ESC><Cmd>call ddu#ui#do_action('itemAction')<CR>
	nnoremap <buffer> a
				\ <Cmd>call ddu#ui#do_action('chooseAction')<CR>
	nnoremap <buffer><silent> q
				\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>

endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()

function! s:ddu_filter_my_settings() abort
	inoremap <buffer> <C-l>
				\ <ESC><Cmd>call ddu#ui#ff#do_action('leaveFilterWindow')<CR>
	inoremap <buffer> <C-q>
				\ <ESC><Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f` to start ddu
2. type `<C-l>` in filter window to leave filter window
3. type `a` to fire chooseAction
4. move cursor to `open` action
5. type `<CR>` to fire `open` action

## Screenshot (if possible)
![hoge](https://github.com/Shougo/ddu-ui-ff/assets/50443168/4b6150e4-1181-4382-b1b4-c70de7044989)

**Comment by kamecha** [comment]
I think that `startFilter` should be applied even after `chooseAction`.

However there are other ui like `ddu-ui-filer` that don't have `startFilter` otpion, So it seems to be difficult from a compatibility point of view.

**Comment by Shougo** [comment]
Fixed.  Please update `ddu-source-action`.
