### ISSUE TITLE
`openFilterWindow` doesn't work well when `startFilter` option is true and fire `redraw` action

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#132]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
there are some problem using `openFilterWindow` like bellow

1. filter window is opened other place before
    1. use `ddu#ui#do_action('closeFilterWindow')`
    2. use `ddu#ui#do_action('redraw', #{ method: 'uiRedraw' })`
    3. use `ddu#ui#do_action('openFilterWindow')`
1. `i` or `A` is inputted to filter window
    1. use `ddu#ui#do_action('redraw', #{ method: 'uiRedraw' })`
    2. use `ddu#ui#do_action('closeFilterWindow')`
    3. use `ddu#ui#do_action('openFilterWindow')`

## Expected
it works well without these problems.

## Environment Information

- ddu-ui-ff version (SHA1):
1b39755

- denops.vim version (SHA1):
b5dfcbc

- deno version(`deno -V` output):
deno 1.38.5

- OS:
WSL2 Ubuntu 22.03.4 LTS

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1846+gf31f260f0
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff

function s:update_ui_layout() abort
	let l:current_options = ddu#custom#get_current()
	if l:current_options->empty()
		return
	endif
        " ↓ this function order seems to be important
	call ddu#ui#do_action('redraw', #{ method: 'uiRedraw' })
	call ddu#ui#do_action('closeFilterWindow')
	call ddu#ui#do_action('openFilterWindow')
endfunction

autocmd VimResized * call s:update_ui_layout()

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start(#{
			\ ui: 'ff',
			\ uiParams: #{
			\   ff: #{
			\     startFilter: v:true,
			\   }
			\ }
			\ })<CR>

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()

function! s:ddu_filter_my_settings() abort
	inoremap <buffer> <C-l>
				\ <ESC><Cmd>call ddu#ui#do_action('leaveFilterWindow')<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f` to start ddu
2. type `<C-l>` in filter window to fire `leaveFilterWindow` action
3. resize vim ( resize terminal window by using mouse ) to fire `s:update_ui_layout`
4. there are some problem depending on the function order above
    -  filter window is opened other place before
    -  `i` or `A` is inputted to filter window ← if the order is above .vimrc, this problem is appeared.

## Screenshot if possible
-  `i` or `A` is inputted to filter window
![hoge](https://github.com/Shougo/ddu-ui-ff/assets/50443168/48425399-548e-45bd-9b10-a551ca69afe1)

- filter window is opened other place before
![hoge](https://github.com/Shougo/ddu-ui-ff/assets/50443168/8b8380c9-671a-4080-b6fc-12eb2abdd504)

**Comment by Shougo** [comment]
Hm...

I should remove `startFilter` feature...

**Comment by Shougo** [comment]
I will remove the feature.  Please wait.

**Comment by Shougo** [comment]
I have removed `startFilter` option.
