### ISSUE TITLE
About the behavior of openFilterWindow when using autocmd and keymap

### ISSUE THREAD

**Issue by yasunori0418** [Shougo/ddu-ui-ff#143]
# Problems summary

The behavior is different when opening the filter manually and when opening the filter with autocmd.

## Expected

There are the following differences when running `openFilterWindow` with autocmd and when running `openFilterWindow` manually using the configured keymap.

- autocmd
    - The list of items will not be updated until you confirm what you entered in the cmdline.
- keymap
    - The list of items is updated to sync with the input in cmdline

I would like to unify the behavior with `keymap` or `autocmd`.
Ideally, the behavior when using `keymap` is the best, but as far as I have checked the specifications,
I think that the behavior when using `autocmd` is the expected behavior.

## Environment Information

- ddu-ui-ff version (SHA1): 5749699

- denops.vim version (SHA1): https://github.com/vim-denops/denops.vim/commit/9dd9ae9da9b8d65916dd44e0e4d881665397de63

- deno version(`deno -V` output): `deno 1.43.6`

- OS: Arch Linux

- neovim/Vim `:version` output:

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled May 26 2024 00:11:37)
Included patches: 1-445
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
const s:repo_path = expand("~/.cache/dpp/repos/github.com")
const s:plugins = [
  \ 'Shougo/ddu.vim',
  \ 'Shougo/ddu-ui-ff',
  \ 'Shougo/ddu-source-file_rec',
  \ 'Shougo/ddu-kind-file',
  \ 'Shougo/ddu-filter-matcher_substring',
  \ 'vim-denops/denops.vim',
\ ]
for plugin in s:plugins
  execute 'set' $'rtp^={s:repo_path}/{plugin}'
endfor

call ddu#custom#patch_global(#{
  \ ui: 'ff',
  \ sourceOptions: #{
    \ _: #{
      \ matchers: ['matcher_substring'],
    \ },
  \ },
  \ kindOptions: #{
    \ defaultAction: 'open',
  \ },
\ })

function! s:ddu_ff_keymaps() abort
  nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer> i
  \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q
  \ <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff call s:ddu_ff_keymaps()
autocmd User Ddu:uiDone ++nested
  \ call ddu#ui#do_action("openFilterWindow")

command! Test call ddu#start(#{sources: ['file_rec']})
```

## How to reproduce the problem from neovim/Vim startup (Required!)

- Vim
    1. `vim -N -u .vimrc`
    2. `:Test`
    3. Enter something from there to search
        - At this time, it will not synchronize with the input and the item list will not be updated until the input is confirmed.
    4. Comment out the autocmd that automatically opens openFilterWindow with Ddu:uiDone
    5. One more steps 1 to 2.
    6. Run `openFilterWindow` with `i` by keymap
        - At this time, the item list will be updated in sync with the input.
- neovim
    1. `nvim -u .vimrc`
    2. Perform the same operations 2 to 6 as in Vim and the same behavior will occur

**Comment by Shougo** [comment]
Reproduced...

**Comment by Shougo** [comment]
```vim
autocmd User Ddu:uiDone ++nested
  \ call ddu#ui#do_action("openFilterWindow")
```

It must be `async_action()`.
