### ISSUE TITLE
Cmdline integration is broken when calling `ddu#ui#get_items()` on CursorMoved

### ISSUE THREAD

**Issue by 4513ECHO** [Shougo/ddu-ui-ff#149]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Cmdline integration is broken when calling `ddu#ui#get_items()` on CursorMoved.

## Expected

Typed charactars should be appeared. Cmdline floatwin should not remained.

## Environment Information

- ddu-ui-ff version (SHA1): [`62e11487913f3f7d68da93793f9ba9afcb04ad00`](https://github.com/Shougo/ddu-ui-ff/commit/62e11487913f3f7d68da93793f9ba9afcb04ad00)

- denops.vim version (SHA1): [`e6eb1ab24c166ee7810218e91abf0b435ec0a4ea`](https://github.com/vim-denops/denops.vim/commit/e6eb1ab24c166ee7810218e91abf0b435ec0a4ea) on v7-pre

- deno version(`deno -V` output): `deno 1.45.2`

- OS: `macOS Sonoma 14.5`

- neovim/Vim `:version` output:

<details>

```
NVIM v0.11.0-dev-3568+g60734dc76-Homebrew
Build type: Release
LuaJIT 2.1.1720049189
Run ":verbose version" for more info
```

</details>

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=/path/to/vim-denops/denops.vim_v7-pre
set runtimepath+=/path/to/Shougo/ddu.vim
set runtimepath+=/path/to/Shougo/ddu-ui-ff
set runtimepath+=/path/to/Shougo/cmdline.vim
set runtimepath+=/path/to/4513ECHO/ddu-source-colorscheme

nnoremap mm <Cmd>call ddu#start(#{
      \ sources: [#{ name: 'colorscheme' }],
      \ kindOptions: #{
      \   colorscheme: #{ defaultAction: 'set' }
      \ },
      \ ui: 'ff',
      \ uiParams: #{
      \   ff: #{
      \     split: 'floating',
      \   },
      \ },
      \ })<CR>
cnoremap <CR> <CR><Cmd>call ddu#ui#do_action('itemAction')<CR>

autocmd User Ddu:uiDone call ddu#ui#async_action('openFilterWindow')
autocmd User Ddu:ui:ff:openFilterWindow call cmdline#enable()
autocmd CursorMoved ddu-ff-* call ddu#ui#get_items()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Type `mm`
2. Type something not appeared
3. Cmdline floatwin is remained even you typed `<CR>`

## Screenshot (if possible)

None.

## Upload the log messages by `:redir` and `:message` (if errored)

None.

**Comment by Shougo** [comment]
It is reproduced.  But it seems feature.
You must not call UI action in autocmd.

**Comment by Shougo** [comment]
Because if you use it, cmdline.vim autocmd handlers are not called.

So

> Cmdline floatwin is remained even you typed <CR>

This problem is occurred.
