### ISSUE TITLE
When a preview window is shown, "redraw" ui action resizes a ff-window but not the preview-window

### ISSUE THREAD

**Issue by kyoh86** [Shougo/ddu-ui-ff#154]
# Problems summary

SSIA

## Expected

The preview-window also be resized.

## Environment Information

- denops.vim
  - f32f02817729129abb3e093fc21e5160512a5673
- ddu.vim
  - b65b10dcd986457b5fa2f007820839d01ab7a215
- ddu-source-file_rec
  - 3771180decc519a3e09c2c4826740a53997883e1
- ddu-kind-file
  - 875d00eefe4285fd419d61c12145fc399c7dd67f
- ddu-ui-ff
  - 7bcf85fc79ca180ea86958244f0161763a80564f
- deno
  - 1.46.2
- OS
  - Ubuntu 24.04.1 LTS
- neovim
  - `v0.11.0-dev-738a84d`

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/rtp/denops.vim
set rtp+=~/rtp/ddu.vim
set rtp+=~/rtp/ddu-source-file_rec
set rtp+=~/rtp/ddu-kind-file
set rtp+=~/rtp/ddu-ui-ff

let g:denops#deno = "~/rtp/bin/deno"

call ddu#custom#patch_global({
  \   "sources": [{
  \     "name": "file_rec",
  \   }],
  \   "kindOptions": {
  \     "file": {"defaultAction": "open"},
  \   },
  \   "ui": "ff",
  \   "uiParams": {
  \     "ff": {
  \       "winRow": "(&lines - min([70, &lines - 8]) - 3) / 2",
  \       "previewRow": "(&lines - min([70, &lines - 8]) - 3) / 2",
  \
  \       "winHeight": "min([70, &lines - 8])",
  \       "previewHeight": "min([70, &lines - 8])",
  \
  \       "winCol": "&columns / 10",
  \       "previewCol": "&columns / 2",
  \
  \       "winWidth": "&columns * 4 / 10 - 2",
  \       "previewWidth": "&columns * 4 / 10 - 2",
  \
  \       "startAutoAction": v:true,
  \       "autoAction": {
  \         "name": "preview",
  \       },
  \
  \       "split": "floating",
  \       "previewFloating": v:true,
  \       "previewSplit": "vertical",
  \     }
  \   }
  \ })
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `:call ddu#start()`
2. Resize terminal window
3. `:call ddu#ui#do_action("redraw", {"method": "uiRedraw"})`

## Screenshot (if possible)

1. `:call ddu#start()`
    - ![wslhost exe 2024_09_07 18_12_15](https://github.com/user-attachments/assets/ca142223-8f84-4f9f-a894-2308e32578f1)

2. Resize terminal window
    - ![New Issue · Shougo_ddu-ui-ff - Google Chrome 2024_09_07 18_15_16](https://github.com/user-attachments/assets/3b2c3c08-39c9-4ade-a925-f107c1d4af9a)

3. `:call ddu#ui#do_action("redraw", {"method": "uiRedraw"})`
    - ![wslhost exe 2024_09_07 18_15_34](https://github.com/user-attachments/assets/fcc4db91-1b33-41fb-b1bc-fc9223b02a01)

**Comment by kyoh86** [comment]
Workaround:

call "closePreviewWindow" and "preview" action after "redraw" action.


```
call ddu#ui#do_action("redraw", {"method": "uiRedraw"})
call ddu#ui#do_action("closePreviewWindow")
call ddu#ui#do_action("preview")
```

**Comment by Shougo** [comment]
Fixed.
