### ISSUE TITLE
itemAction cannot be executed from the filter view due to an error "Too many arguments for function: getcurpos"

### ISSUE THREAD

**Issue by creasty** [Shougo/ddu-ui-ff#17]
## Why

https://github.com/Shougo/ddu-ui-ff/blob/76bf9749ebecb3c37dab777a98c847bde1cf8fdc/denops/%40ddu-uis/ff.ts#L561

```
autocmd FileType ddu-ff-filter
  \ nnoremap <buffer> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
```

<img width="1896" alt="Screen Shot 2022-03-11 at 1 07 30" src="https://user-images.githubusercontent.com/1695538/157704543-94f21def-d5e5-4750-9a97-1c203577f8f9.png">

**Comment by creasty** [comment]
Seems like the function signature differs in vim and neovim.

### vim

https://vimhelp.org/builtin.txt.html#builtin-functions

```
getcurpos([{winnr}])            List    position of the cursor
```

### nvim (0.6.1)

```
							*getcurpos()*
getcurpos()	Get the position of the cursor.  This is like getpos('.'), but
		includes an extra "curswant" in the list:
		    [0, lnum, col, off, curswant] ~
		The "curswant" number is the preferred column when moving the
		cursor vertically.  Also see |getpos()|.
		The first "bufnum" item is always zero.

 		This can be used to save and restore the cursor position: >
 			let save_cursor = getcurpos()
 			MoveTheCursorAround
 			call setpos('.', save_cursor)
<		Note that this only works within the window.  See
		|winrestview()| for restoring more state.

```

**Comment by Shougo** [comment]
Oh, nvim 0.7.0 supports the feature.

**Comment by creasty** [comment]
FYI, the line() function in both vim and neovim takes winid as a second argument.

> line({expr} [, {winid}])        [Number](https://vimhelp.org/eval.txt.html#Number)  line nr of cursor, last line or [mark](https://vimhelp.org/motion.txt.html#mark)

https://vimhelp.org/builtin.txt.html#builtin-functions

> line({expr} [, {winid}])	[Number](https://neovim.io/doc/user/eval.html#Number)	line nr of cursor, last line or [mark](https://neovim.io/doc/user/motion.html#mark)

https://neovim.io/doc/user/builtin.html

**Comment by Shougo** [comment]
Oh, really?  When it is changed?

**Comment by Shougo** [comment]
Fixed.

**Comment by creasty** [comment]
Thank you.
