### ISSUE TITLE
Word highlight remains after clearing input

### ISSUE THREAD

**Issue by creasty** [Shougo/ddu-ui-ff#21]
https://user-images.githubusercontent.com/1695538/158011959-fb9a9f9a-3001-45bf-ae77-a35765c3cd74.mov

**Comment by Shougo** [comment]
Why don't you upload the minimal vimrc???

**Comment by Shougo** [comment]
The problem is only occurred when reversed.  So the minimal vimrc is required!

**Comment by Shougo** [comment]
If you don't upload the minimal vimrc means "It must be reproduceable with any vimrc".
But the problem is not.

**Comment by creasty** [comment]
Oh sorry, slipped my mind.

**Comment by matsui54** [comment]
@creasty 
Are you using [ddu-filter-fzy](https://github.com/matsui54/ddu-filter-fzy)? This problem occurs with with filter.

**Comment by creasty** [comment]
> Are you using ddu-filter-fzy? This problem occurs with this filter.

@matsui54 In fact I am!

So I take it's not fixed by https://github.com/Shougo/ddu-ui-ff/commit/2f8c8a2d4269bd78c0251d4aca6fe8eaaa998b01.

**Comment by matsui54** [comment]
I have fixed the filter now. Can you update and check it?
https://github.com/matsui54/ddu-filter-fzy/commit/b6ad62217f1ca69c5933a83f6c9560ca4c8de14f

**Comment by Shougo** [comment]
I don't test ddu-filter-fzy.
It was reproduced with reversed plus ddu-filter-matcher_substring.

**Comment by creasty** [comment]
I've tested and here's the result:

- ❌ https://github.com/Shougo/ddu-ui-ff/commit/2f8c8a2d4269bd78c0251d4aca6fe8eaaa998b01 alone
- ✅ https://github.com/matsui54/ddu-filter-fzy/commit/b6ad62217f1ca69c5933a83f6c9560ca4c8de14f alone
- ✅ https://github.com/Shougo/ddu-ui-ff/commit/2f8c8a2d4269bd78c0251d4aca6fe8eaaa998b01 + https://github.com/matsui54/ddu-filter-fzy/commit/b6ad62217f1ca69c5933a83f6c9560ca4c8de14f

Thank you both!
