### ISSUE TITLE
Multiple filter windows are created on incremental update

### ISSUE THREAD

**Issue by matsui54** [Shougo/ddu-ui-ff#27]
## Problem
Filter windows are created every time items are enqueued.

## Environment
Neovim v0.7.0

## Minimal vimrc
```vim
set runtimepath+=~/.cache/dein/repos/github.com/vim-denops/denops.vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddu.vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddu-ui-ff
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddu-kind-file
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/ddu-source-file_rec

nnoremap <Space>f
      \ <Cmd>call ddu#start({'sources': [{'name': 'file_rec'}]})<CR>

call ddu#custom#patch_global({
      \ 'ui': 'ff',
      \ 'uiParams': {'ff': {
      \   'split': 'floating',
      \   'autoResize': v:true,
      \ }},
      \ })

autocmd FileType ddu-ff call s:ddu_ff_my_settings()
function! s:ddu_ff_my_settings() abort
  nnoremap <buffer> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer> <CR> <Esc><Cmd>close<CR>
endfunction
```

## Reproduce steps
1. start nvim and cd to large directory (which has more than 200000 files)
2. execute `<Space>f` (start ddu)
3. type `i` (open filter window) immediately after the ddu window appears
4. type `<CR>` (close filter window) immediately after the filter window appears
5. wait for items are enqueued

## Screenshot
![ddu_incremental](https://user-images.githubusercontent.com/63794197/159410820-9001c5d3-54d5-46de-898b-2c8cc2b9e5aa.gif)

**Comment by matsui54** [comment]
Thank you, but though I closed the filter window, the filter window is automatically opened when the items are enqueued.

![ddu_incremental_bug](https://user-images.githubusercontent.com/63794197/159493266-71ebbcc7-2e31-4483-8ac0-bb614d9aa563.gif)

**Comment by Shougo** [comment]
Fixed.  Please update.

**Comment by matsui54** [comment]
It seems fixed. Thank you!
