### ISSUE TITLE
[Feature Request] Customizable preview window position

### ISSUE THREAD

**Issue by ryota2357** [Shougo/ddu-ui-ff#39]
I want to set the column/row position of the preview window.

Could you add `previewCol` and `previewRow`, like `winCol` and `winRow` ?

or, could you fix the following problem?

If we call `ddu#ui#ff#do_action('preview')` in `ddu-ff`, the preview window is shown like this.
<img width="783" alt="スクリーンショット 2022-05-22 14 45 01" src="https://user-images.githubusercontent.com/61523777/169680739-2a890909-5e93-411d-930d-80bd88846aa3.png">

but, if we call it in `ddu-ff-filter`, the preview window is shown at strange position.
<img width="783" alt="スクリーンショット 2022-05-22 14 45 28" src="https://user-images.githubusercontent.com/61523777/169680745-85511086-5188-4cfc-b419-7d300d701ae2.png">

**Comment by Shougo** [comment]
Fixed.
