### ISSUE TITLE
Filter window cannot fixed.

### ISSUE THREAD

**Issue by nekowasabi** [Shougo/ddu-ui-ff#46]
# Problems summary
When using ddu-ui-ff to display a filter window, the window division is not fixed and the window width changes repeatedly.

## Expected
Filter windows is fixed.

## Environment Information

- ddu.vim version (SHA1):
990b0c6d14a6be27682be73fdc3d9a835d62f765

- denops.vim version (SHA1):
a104cbff7e47a63978cfb3921da4333465fc6d15

- deno version(`deno -V` output):
1.22.2

- OS: Windows11

- neovim/Vim `:version` output:
GVim 8.2
patch 1-3438

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

if empty(glob('/path/to/vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('/path/to/vim/plugged')
Plug 'vim-denops/denops.vim'
Plug 'Shougo/ddu.vim'
Plug 'Shougo/ddu-ui-ff'
Plug 'Shougo/ddu-filter-matcher_substring'
Plug 'Shougo/ddu-kind-file'
Plug 'Shougo/ddu-ui-filer'
Plug 'Shougo/ddu-commands.vim'
call plug#end()

 " ddu
 " Specify matcher.
 call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sourceOptions' : {
    \     '_' : {
    \       'ignoreCase': v:true,
    \     },
    \   },
    \ })
 
nnoremap <silent> <space><space> <Cmd>Ddu
   \ -name=search mr -ui-param-startFilter=v:true<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Boot Gvim
2. Key type `<Space><Space>`

## Screenshot (if possible)

![ddu](https://user-images.githubusercontent.com/3657473/175252789-4c43ecd7-8246-4fe3-93d2-b118bcab1f41.gif)

**Comment by Shougo** [comment]
Please fix the reproduce instruction.

And your screenshot is not same with minimal vimrc.
It is confusing for me.

**Comment by Shougo** [comment]
I have tested it agein by `nnoremap <silent> <space><space> <Cmd>Ddu
      \ -name=search file -ui-param-startFilter=v:true<CR>`.
But I cannot reproduce it.

**Comment by Shougo** [comment]
This minimal vimrc is better:

```vim
set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-commands.vim
set rtp+=~/work/ddu-ui-ff

call ddu#custom#patch_global({
      \   'ui': 'ff',
      \   'sourceOptions' : {
      \     '_' : {
      \       'ignoreCase': v:true,
      \     }
      \   },
      \ })

nnoremap <silent> <space><space> <Cmd>Ddu
      \ -name=search mr -ui-param-startFilter=v:true<CR>
```

**Comment by Shougo** [comment]
```
GVim 8.2
patch 1-3438
```

It seems old.  Please use nightly build instead.

**Comment by Shougo** [comment]
> Environment Information

`ddu-ui-ff` is the latest?  And please check `ddu-ui-ff` window is `winfixheight`.

**Comment by Shougo** [comment]
@nekowasabi Please test it on the other environments.
In neovim and Linux.

**Comment by Shougo** [comment]
OK.  I get it.  If `winfixheight` is not set, the problem is reproduced.

**Comment by nekowasabi** [comment]
@Shougo 
Update to nightly Gvim and update ddu-ui-ff.
So, it worked.

Thank you!!
