### ISSUE TITLE
Add support for vim's popup window

### ISSUE THREAD

**Issue by kshpytsya** [Shougo/ddu-ui-ff#48]
Please consider adding support for vim's popup window which is an alternative to neovim's floating window mechanism.

https://github.com/vim/vim/blob/master/runtime/doc/popup.txt
See also: https://github.com/vim/vim/issues/4063

**Comment by Shougo** [comment]
I don't want to add the feature.

Because Vim's popup window feature is not same with floating window feature.
Popup window does not support window enter.
`ddu-ui-ff` depends on the behavior.  So I cannot implement it.

Popup window is built for completion window like UI.

**Comment by Shougo** [comment]
> See also: https://github.com/vim/vim/issues/4063

Have you read the discussion entirely??

**Comment by Shougo** [comment]
If you really need the feature, please see this.

https://github.com/vim/vim/pull/7555

The feature must be included.   It is Vim's implementation issue instead.
