### ISSUE TITLE
Option 'previewwindow' in the ddu-ff preview-window is not set

### ISSUE THREAD

**Issue by hereGittyGitty** [Shougo/ddu-ui-ff#53]
Hi Shougo. 

Thx a lot for the `ddu` series of plugins of course. (And a late 'thx-a-lot' for the [denite.nvim](https://github.com/Shougo/denite.nvim), [unite.vim](https://github.com/Shougo/unite.vim)... plugins as well). Still can't figure out what your avatar on github is meant to be (its not a zebra-dragon is it? 😉)

# Problems summary
When invoking the `preview` _action_ on a `file` _kind_/_source_ the emerging _preview window_ has its `previewwindow` _option_ set to `nopreviewwindow`. 
As of now there is only on big problem I have with this fact. I really like to use the [vim-preview](https://github.com/skywind3000/vim-preview) plugin to scroll the _preview window_ while leaving the cursor in the `denite`-window and I am missing this functionality in `ddu`.

## Expected
I would expect the _ddu-ff preview window_ to have its `previewwindow` option set to `previewwindow`

## Environment Information

- ddu-ui-ff version (SHA1): `c5958937bd73b262642aec93f9ff0623c4250e67`

- denops.vim version (SHA1): `d7db28587bb281f9fcf56d4986e313025e250295`

- deno version(`deno -V` output): `deno 1.21.1`

- OS: `GNU/Linux`

- neovim/Vim `:version` output:
```
NVIM v0.8.0-dev-1071-gf98cff957
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by lorenz@chicken

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set nocompatible

set runtimepath+=/usr/local/src/neovim_minimal_stuff/denops.vim
set runtimepath+=/usr/local/src/neovim_minimal_stuff/ddu.vim
set runtimepath+=/usr/local/src/neovim_minimal_stuff/ddu-source-file
set runtimepath+=/usr/local/src/neovim_minimal_stuff/ddu-kind-file
set runtimepath+=/usr/local/src/neovim_minimal_stuff/ddu-ui-ff
set runtimepath+=/usr/local/src/neovim_minimal_stuff/ddu-commands.vim
set runtimepath+=/usr/local/src/neovim_minimal_stuff/vim-preview

filetype plugin indent on

" ddu#custom#patch_global ui: ff --- {{{
call ddu#custom#patch_global({
    \ 'ui': 'ff',
    \ })
" }}}

" ddu_ff_my_settings --- {{{
autocmd FileType ddu-ff call s:ddu_ff_my_settings()
function! s:ddu_ff_my_settings() abort
  nnoremap <buffer><silent> p
        \ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
endfunction
" }}}

" vim-preview --- {{{
noremap <silent> <A-k> :PreviewScroll -1<cr>
noremap <silent> <A-j> :PreviewScroll +1<cr>
inoremap <silent> <A-k> <c-\><c-o>:PreviewScroll -1<cr>
inoremap <silent> <A-j> <c-\><c-o>:PreviewScroll +1<cr>
" }}}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. start a _minimal_ _neovim_ with the command: `VIMRUNTIME=/usr/local/src/neovim/runtime /usr/local/src/neovim/build/bin/nvim --clean -u /usr/local/src/neovim_minimal_stuff/minimal_init.vim`
2. execute `Ddu file`
3. move the cursor to a _file entry_
4. press the the `p`-key (mapping for the `preview` _action_) to open the
   _preview window_
5. execute the command `wincmd k` to focus the _preview window_
6. query the 'previewwindow'-option by executing the command `set
   previewwindow?`

## Screenshot (if possible)
![ddu-ui-ff-nopreviewwindow](https://user-images.githubusercontent.com/2407498/189539101-030e7fc1-0f4f-4234-8fd3-40f716ba1365.png)

## Further remarks:

If this is by design, would it be possible to add the feature of scrolling the _preview window_ while keeping the cursor-focus on the _ddu-ff_ window?

Thx a lot and have a good one ^^

**Comment by Shougo** [comment]
Fixed.

> Thx a lot for the ddu series of plugins of course. (And a late 'thx-a-lot' for the [denite.nvim](https://github.com/Shougo/denite.nvim), [unite.vim](https://github.com/Shougo/unite.vim)... plugins as well). Still can't figure out what your avatar on github is meant to be (its not a zebra-dragon is it? wink)

The icon is the dragon knight head instead of zebra.

**Comment by hereGittyGitty** [comment]
> Fixed.

Nice... thank you :)
> The icon is the dragon knight head instead of zebra.

Got it...
