### ISSUE TITLE
Doesn't restore the previous cursor position resuming

### ISSUE THREAD

**Issue by creasty** [Shougo/ddu-ui-ff#63]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

## Expected

Related: https://github.com/Shougo/ddu-ui-ff/issues/54

## Environment Information

- ddu-ui-ff version (SHA1): 0e889a3ac48f20f4392a5547c051d311cad82e36

- denops.vim version (SHA1): 8f3899de3d3add07105221262dca90a31c4c2d4c

- deno version(`deno -V` output): 1.30.3

- OS:

- neovim/Vim `:version` output: v0.8.3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if has('vim_starting')
  let s:config_path = stdpath('config')
  for s:repo in [
    \ 'vim-denops/denops.vim',
    \ 'Shougo/ddu.vim',
    \ 'Shougo/ddu-ui-ff',
    \ 'Shougo/ddu-kind-file',
    \ 'matsui54/ddu-filter-fzy',
  \ ]
    let s:path = s:config_path . '/dein/repos/github.com/' . s:repo
    let &g:rtp .= ',' . s:path
  endfor
endif

call ddu#custom#patch_global({
  \ 'ui': 'ff',
  \ 'uiParams': {
    \ 'ff': {
      \ 'split': 'floating',
      \ 'filterSplitDirection': 'floating',
    \ },
  \ },
  \ 'sourceOptions': {
    \ 'ghq': {
      \ 'matchers': ['matcher_fzy'],
    \ },
  \ },
\ })

command! Open call s:open()
function! s:open() abort
  call ddu#start({
    \ 'name': 'ghq',
    \ 'sources': [{ 'name': 'ghq' }],
    \ 'uiParams': { 'ff': { 'startFilter': v:true } },
    \ 'resume': v:true,
  \ })
endfunction

augroup _init_ddu
  autocmd!
  autocmd FileType ddu-ff call <SID>init_ddu()
  autocmd FileType ddu-ff-filter call <SID>init_ddu()
augroup END

function! s:init_ddu() abort
  nnoremap <buffer> <Esc> <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer> <C-q> <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  inoremap <buffer> <C-q> <Cmd>call ddu#ui#ff#do_action('quit')<CR>

  nnoremap <buffer> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  inoremap <buffer> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer> <C-j> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  inoremap <buffer> <C-j> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>

  if &filetype ==# 'ddu-ff'
    setl cursorline
  endif
  if &filetype ==# 'ddu-ff-filter'
    inoremap <buffer> <C-p> <Cmd>call ddu#ui#ff#execute("call cursor(line('.')-1,0)<Bar>redraw")<CR>
    inoremap <buffer> <C-n> <Cmd>call ddu#ui#ff#execute("call cursor(line('.')+1,0)<Bar>redraw")<CR>
  endif
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open ddu-ui by `:Open`
2. Enter query (optional)
3. Move cursor
4. Quit with `<C-q>`
5. Reopen ddu-ui

**Comment by Shougo** [comment]
Sorry.  It is expected behavior.
The resume cursor is disabled when startFilter is enabled.

**Comment by Shougo** [comment]
Because it breaks autoAction.

**Comment by creasty** [comment]
> The resume cursor is disabled when startFilter is enabled.

Any way I can mimic the previous behavior without changing the plugin itself?

My usual routine heavily depends on this specific behavior; In fact, it's one of the reasons I don't/can't use other plugins, there's no alternative.
So I would really appreciate it if you could give it another thought.
Like making the resume cursor available when the autoAction is disabled.

**Comment by Shougo** [comment]
> Like making the resume cursor available when the autoAction is disabled.

I have implemented the feature.  Please update.

**Comment by creasty** [comment]
Thanks a lot!
