### ISSUE TITLE
Layout issue with floating filter window display

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#69]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When positioning the filter window at the bottom using float display, the layout becomes distorted.

## Expected
Filter and source borders are displayed properly and highlighting is set correctly.

## Environment Information

- ddu-ui-ff version (SHA1):
  - `87e95b80226f591f53b5e2afed1d9f16838a2d38`

- denops.vim version (SHA1):
  - `8f3899de3d3add07105221262dca90a31c4c2d4c`

- deno version(`deno -V` output):
  - `deno 1.30.3`

- OS:
  - `Ubuntu 22.04` (WSL2)

- neovim/Vim `:version` output:
  ```
  NVIM v0.9.0-dev-1088+gd66832c76
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  ```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
syntax enable
filetype plugin indent on

set rtp+=~/path/to/denops.vim
set rtp+=~/path/to/ddu.vim
set rtp+=~/path/to/ddu-ui-ff
set rtp+=~/path/to/ddu-kind-file
set rtp+=~/path/to/ddu-source-file_rec

let s:ddu_config_json =<< trim MARK
	{
		"uiParams": {
			"ff": {
				"split": "floating",
				"floatingBorder": "rounded",
				"startFilter": true,
				"filterFloatingPosition": "bottom",
				"filterSplitDirection": "floating"
			}
		}
	}
MARK

let s:ddu_config_json = s:ddu_config_json->join('')->json_decode()

call ddu#custom#patch_global(s:ddu_config_json)

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [{'name': 'file_rec', 'params': {}}],
			\ })<CR>

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f`

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/50443168/225976706-89cc0802-163b-4399-a190-b141e8df44a7.png)

**Comment by Shougo** [comment]
Fixed.

**Comment by kamecha** [comment]
Sorry to add to closed thread.

Thank you for fixing the border layout.
However there is difference in the highlights of the borders between the filter window and the source window.

Could you please consider adjusting the highlight colors of the borders to be consistent between the filter window and the source window?

![image](https://user-images.githubusercontent.com/50443168/226096843-b62e5e39-b4ee-4a0a-8180-209160c2b022.png)

**Comment by Shougo** [comment]
Fixed.  Please update.
