### ISSUE TITLE
intentionally disabling cursor resume

### ISSUE THREAD

**Issue by dmfay** [Shougo/ddu-ui-ff#72]
# Problems summary

Related to #63 but I have the opposite issue: I never want to resume and always want my cursor to start at the top.

ddu-ui-ff does not have a toggle for this feature currently.

I tried adding `autoAction: #{name: 'noop'}` to my configuration since `startFilter` + `autoAction` disables the feature. This does prevent cursor resume but adds "Invalid UI action: noop" warnings.

## Expected

Not expected as such but I think a `cursorResume` default-true boolean toggle would work fine!

## Environment Information

- ddu-ui-ff version (SHA1): f069b00773858122002720b94625b2b820df34db
- denops.vim version (SHA1): 8f3899de3d3add07105221262dca90a31c4c2d4c
- deno version(`deno -V` output):
```
deno 1.31.1 (release, x86_64-unknown-linux-gnu)
v8 11.0.226.13
typescript 4.9.4
```
- OS: Arch Linux
- neovim/Vim `:version` output:
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if has('vim_starting')
  let s:config_path = stdpath('cache')
  for s:repo in [
    \ 'vim-denops/denops.vim',
    \ 'Shougo/ddu.vim',
    \ 'Shougo/ddu-ui-ff',
    \ 'Shougo/ddu-kind-file',
    \ 'shun/ddu-source-buffer',
    \ 'Shougo/ddu-filter-matcher_substring',
  \ ]
    let s:path = s:config_path . '/../dein/repos/github.com/' . s:repo
    let &g:rtp .= ',' . s:path
  endfor
endif

call ddu#custom#patch_global(#{
  \   ui: 'ff',
  \   volatile: v:true,
  \   uiParams: #{
  \     ff: #{
  \       startFilter: v:true,
  \       ignoreEmpty: v:false,
  \       autoResize: v:false,
  \     }
  \   },
  \   kindOptions: #{
  \     file: #{
  \       defaultAction: 'open',
  \     },
  \   },
  \   sources: [
  \     #{ name: 'buffer', },
  \   ],
  \   sourceParams: #{
  \     buffer: #{
  \       orderby: 'desc'
  \     },
  \   },
  \ })

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer> <CR>
    \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  inoremap <buffer> <Esc>
    \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  inoremap <buffer> <C-j>
    \ <Cmd>call ddu#ui#ff#execute(
    \ "call cursor(line('.')+1,0)<Bar>redraw")<CR>
  inoremap <buffer> <C-k>
    \ <Cmd>call ddu#ui#ff#execute(
    \ "call cursor(line('.')-1,0)<Bar>redraw")<CR>
endfunction

nnoremap <space>b :call ddu#start(#{sources: [#{name: 'buffer'}]})<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open multiple buffers
2. \<Space>-b to open ddu-ui-ff with buffer source
3. \<C-j> to move down the list; note ddu status line updates with current cursor row
4. \<Enter> to open the file or <Esc> to cancel and exit ddu (same result either way)
5. \<Space-b> to open ddu-ui-ff again: cursor row is unchanged from step 3

**Comment by Shougo** [comment]
Please set `cursorPos` option.

```
						*ddu-ui-ff-param-cursorPos*
cursorPos	(number)
		Select {number} candidate.
```
