### ISSUE TITLE
split param is not work when filer is open

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#75]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When I use ddu-ui-ff and ddu-ui-filer with different split params, these settings is not work.
For example, when I use ddu-ui-ff with `split: floating` and ddu-ui-filer with `split:vertical` ...
- ff -> filer
  1. open ff float window
  2. try to open filer vertical window while keeping ff float window open
  3. filer window's split is not vertical
- filer -> ff
  1. open filer vertical window
  2. try to open ff float window while keeping filer vertical window open
  3. ff window's split is not float

## Expected
- ff -> filer
  1. open ff float window
  2. try to open filer vertical window while keeping ff float window open
  3. **open filer vertical window** <- this behavior
- filer -> ff
  1. open filer vertical window
  2. try to open ff float window while keeping filer vertical window open
  3.  **open ff float window** <- this behavior

## Environment Information

- ddu-ui-ff version (SHA1):
  `36b08deb8cafb8b6ceb9b677bf425f479fca3ee7`
- ddu-ui-filer version(SHA1):
  `da7d1d5d3c97113c8b10e9fc104f2e312e854999`
- denops.vim version (SHA1):
  `8f3899de3d3add07105221262dca90a31c4c2d4c`
- deno version(`deno -V` output):
  `deno 1.30.3`
- OS:
↓WSL2
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
- neovim/Vim `:version` output:
```
NVIM v0.9.0-dev-1088+gd66832c76
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=path/vim-denops/denops.vim
set rtp+=path/Shougo/ddu.vim
set rtp+=path/Shougo/ddu-ui-ff
set rtp+=path/Shougo/ddu-ui-filer
set rtp+=path/Shougo/ddu-source-file
set rtp+=path/Shougo/ddu-source-file_rec
let s:ddu_config_json =<< trim MARK
	{
		"uiParams": {
			"ff": {
				"split": "floating"
			},
			"filer": {
				"split": "vertical"
			}
		}
	}
MARK

let s:ddu_config_json = s:ddu_config_json->join('')->json_decode()

call ddu#custom#patch_global(s:ddu_config_json)

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [{'name': 'file_rec', 'params': {}}],
			\ })<CR>
nmap <silent> [ddu]e <Cmd>call ddu#start({
			\ 'ui': 'filer',
			\ 'sources': [{'name': 'file', 'params': {}}],
			\ })<CR>

```

## How to reproduce the problem from neovim/Vim startup (Required!)

- ff -> filer
  1. type `<Space>` `u` `f` 
  2. type `<Space>` `u` `e` keeping the ff floating window
- filer -> ff
  1. type `<Space>` `u` `e`
  2. type `<Space>` `u` `f` keeping the filer vertical window

## Screenshot (if possible)
- ff -> filer

| ff | filer |
|---|---|
| ![image](https://user-images.githubusercontent.com/50443168/231985937-5841dae1-512b-42d2-af10-7d118d009ad8.png) |  ![image](https://user-images.githubusercontent.com/50443168/231986057-e407d7b8-0667-408a-a2e1-4220e58a425c.png) |
- filer -> ff

| filer | ff |
|---|---|
|![image](https://user-images.githubusercontent.com/50443168/231986323-4e54d902-e717-48a1-8498-8707edd064ef.png) | ![image](https://user-images.githubusercontent.com/50443168/231986387-5363ef8d-93b8-40a5-b6f4-c21b0d3ce6fc.png) |

**Comment by Shougo** [comment]
Sorry. it(dynamic UI change) is not supported behavior.

**Comment by kamecha** [comment]
Oh... 😭 
But I understand the behavior is actually a part of the plugin's intended functionality. Thank you for letting me know. 👍

**Comment by Shougo** [comment]
I have implemented the feature.
Please update `ddu.vim`.

**Comment by kamecha** [comment]
Thanks for adding the requested feature!
