### ISSUE TITLE
If search results is zero, the item window remains, when filtering items while displaying the preview window.

### ISSUE THREAD

**Issue by flow6852** [Shougo/ddu-ui-ff#79]
**Warning: i solved the problem with minimal init.vim and no
Reproduction Instructions. **

## Conditions

1. neovim
2. set `split` to `'floating'`
3. preview window is displayed.

## Problem

Only the preview window disappears and the cursor moves to the original window while the item window remains.

## Expected.

Either of the following

1. the preview window and the window for the item remain and the cursor remains in the item window. 2.
2. the item window disappears and the cursor moves to the original window.

## Environment Information

- ddu-ui-ff version (SHA1):

36a0c44165ef081740b8721c7a8a4fe3b2a93e90

- denops.vim version (SHA1):

d7a15615f86830e9464c30f761a3911f619b38b3

- deno version (`deno -V` output):

deno 1.32.5

- OS:

ArchLinux

- neovim/Vim `:version` output:

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin manager (Required!)

```vimscript

set runtimepath^=~/.vim runtimepath+=~/.vim/after
set runtimepath+=~/.vim/plugged/denops.vim
set runtimepath+=~/.vim/plugged/ddu.vim
set runtimepath+=~/.vim/plugged/ddu-ui-ff
set runtimepath+=~/.vim/plugged/ddu-source-file
set runtimepath+=~/.vim/plugged/ddu-kind-file
set runtimepath+=~/.vim/plugged/ddu-filter-matcher_substring

let &packpath = &runtimepath

" keybind
nmap <silent> ;f <Cmd>call ddu#start(#{
    \   ui: 'ff',
    \   uiParams: #{
    \       ff: #{
    \         split: "floating",
    \         highlights: {'selected': 'Statement'},
    \         winCol: &columns/8 ,
    \         winWidth: 15 ,
    \         winRow: &lines/8,
    \         winHeight: 10 ,
    \         autoAction: {'name':'preview'},
    \         startFilter : v:false
    \       },
    \   },
    \   sourceOptions : #{
    \       _: #{
    \           matchers: ['matcher_substring']
    \       }
    \   },
    \   sources: [#{
    \      name: "file",
    \   }]})<CR>

augroup DduKeyMap
  au!
  autocmd FileType ddu-ff call s:ddu_my_settings()
  autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
augroup End

function! s:ddu_my_settings() abort
  " global 
  nnoremap <buffer><silent> <Esc>
    \ <Cmd>call ddu#ui#do_action('quit')<CR>

  nnoremap <buffer><silent> i
    \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>

  nnoremap <buffer><silent> p
    \ <Cmd>call ddu#ui#do_action('preview')<CR>
endfunction

function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR> <Esc><Cmd>close<CR>
  inoremap <buffer><silent> <Esc> <Esc><Cmd>close<CR>

  nnoremap <buffer><silent> <CR> <Cmd>close<CR>
  nnoremap <buffer><silent> <Esc> <Cmd>close<CR>
endfunction
```

## How to reproduce from neovim/Vim startup (Required!)

1. exec ddu#start
2. Open filter window
3. do preview action
4. search for elements not in item

## screenshot (if possible)

https://user-images.githubusercontent.com/42508708/236609259-03cde89a-1b18-4132-9324-3e6133269aec.mp4

**Comment by Shougo** [comment]
You must not execute `:close` directory.
Please read the documentation.

```vim
function! s:ddu_filter_my_settings() abort
  inoremap <buffer> <CR>
        \ <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  inoremap <buffer> <ESC>
        \ <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  nnoremap <buffer> <CR>
        \ <Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  nnoremap <buffer> <ESC>
        \ <Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
endfunction
```

**Comment by Shougo** [comment]
It is just keymappings problem.
