### ISSUE TITLE
Cursor move to the left

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/ddu-ui-ff#85]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

When calling `ddu#ui#do_action('quit')` from insert mode of filter, the cursor position is shifted to the left when returning to the original buffer.

## Expected

Keep the cursor position.

## Environment Information

Latest

- ddu-ui-ff version (SHA1): 0de01b69bbcde584e13b0e143cd611d14445e1c4

- denops.vim version (SHA1): 949a52412d35d56354f69bbbade6bcfe2951b8d6

- deno version(`deno -V` output): deno 1.33.4

- OS:

- neovim/Vim `:version` output: NVIM v0.10.0-dev-0788394

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/ddu.vim
set runtimepath+=/path/to/ddu-ui-ff
set runtimepath+=/path/to/ddu-source-file_rec
set runtimepath+=/path/to/ddu-filter-matcher_substring
set runtimepath+=/path/to/ddu-kind-file

call ddu#custom#patch_global({
      \ 'sources': [{'name': 'file_rec'}],
      \ 'ui': 'ff',
      \ 'uiParams': {
      \   'ff': {
      \     'startFilter': v:true,
      \   },
      \ },
      \ 'sourceOptions': {
      \   '_': {
      \       'ignoreCase': v:true,
      \       'matchers': ['matcher_substring'],
      \   },
      \ },
      \ 'kindOptions': {
      \   '_': {
      \     'defaultAction': 'open',
      \   },
      \ },
      \})

augroup my-ddu-ff
  autocmd!
  autocmd FileType ddu-ff-filter call <SID>ddu_ff_filter_mapping()
augroup END

function! s:ddu_ff_filter_mapping() abort
  inoremap <buffer><silent> <Esc> <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

set debug=msg
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start by call `ddu#start({})`.
2. Close ddu with `<Esc>`.
3. You can see that the cursor is shifted to the left.

## Screenshot (if possible)

The cursor that was over the "r" has moved one position to the left.

![cursor-move](https://github.com/Shougo/ddu-ui-ff/assets/82267684/80ea70f0-2f93-4b9f-b56c-74bbe3ccd8b5)

**Comment by Shougo** [comment]
OK.  Fixed.

**Comment by uga-rosa** [comment]
Still happens when the cursor is at the end of a line.
![cursor-move](https://github.com/Shougo/ddu-ui-ff/assets/82267684/0b2e70c4-fe4d-4b0b-95ae-da2653a65339)

**Comment by Shougo** [comment]
Reproduced.  Too bad.  I cannot fix the problem.
I will update FAQ later.
