### ISSUE TITLE
terminanl preview does not work well

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#90]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When I use terminal previewer with ddu-kind-file, it is unable to preview continuously.

## Expected
preview contents continuously with terminal.

## Environment Information

- ddu-ui-ff version (SHA1):
  - 919ac390b6b09ca37634b79bd12e47debc718f1d

- denops.vim version (SHA1):
  - 3b489d50ba2e034c829a09475a4002176bffbef7

- deno version(`deno -V` output):
  - deno 1.30.3

- OS:
  - WSL2 Ubuntu22.04

- neovim/Vim `:version` output:
NVIM v0.9.0-dev-1088+gd66832c76
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file_rec
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\	'ff': {
			\		'autoAction': {
			\			'name': 'preview',
			\			'params': {
			\				'previewCmds': ['less', '+%b', '%s']
			\			}
			\		}
			\	}
			\ },
			\ 'sources': [{'name': 'file_rec', 'params': {}}],
			\ })<CR>

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. open neovim. ()
2. type `<Space>` `u` `f`
3. after previewd, type `j` for move cursor to down
4. cursor is now displayer in terminal preview buffer?

## Screenshot (if possible)
![ddu-ui-ff](https://github.com/Shougo/ddu-ui-ff/assets/50443168/a9efa713-53ef-44ce-be92-795021cdc0a3)

**Comment by Shougo** [comment]
Fixed.
