### ISSUE TITLE
New `ddu-ff-filter-default` can be opened for many times

### ISSUE THREAD

**Issue by ryu-ichiroh** [Shougo/ddu-ui-ff#91]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

## Expected

`ddu-ff-filter-default` should be opened only once.

## Environment Information

- ddu-ui-ff version (SHA1): 15196ec280933905bea2f6fdd537334213bf87df

- denops.vim version (SHA1): 3b489d50ba2e034c829a09475a4002176bffbef7

- deno version(`deno -V` output): deno 1.32.2

- OS: MacOS 13.4 (22F66)

- neovim/Vim `:version` output: NVIM v0.9.0, Build type: Release, LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
packadd denops.vim
packadd ddu.vim
packadd ddu-ui-ff
packadd ddu-filter-matcher_substring
packadd ddu-kind-file
packadd ddu-source-file_rec


call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'uiParams': {
    \     'ff': { 'startFilter': v:true },
    \   },
    \   'sourceOptions': {
    \     '_': { 'matchers': ['matcher_substring'] },
    \   },
    \   'kindOptions': {
    \     'file': { 'defaultAction': 'open' }
    \   }
    \ })

nmap <space>f <Cmd>call ddu#start(#{ sources: [#{ name: 'file_rec' }] })<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. open with minimal vimrc
2. press `<space>f` to open ddu ff
3. press `<Esc>`
4. press `<space>f` again

## Screenshot (if possible)
<img width="210" alt="Screenshot 2023-06-06 at 16 19 13" src="https://github.com/Shougo/ddu-ui-ff/assets/121105839/f48b1cb4-dd1b-487f-bd19-6117da211064">

## Upload the log messages by `:redir` and `:message` (if errored)

No message

**Comment by Shougo** [comment]
Fixed.
