### ISSUE TITLE
when I close ddu, the mode is INSERT not NORMAL.

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#96]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
Open the ddu ,open filter window then close the ddu with `ddu#ui#ff#do_action('quit')` in insert mode, and the mode is INSERT not NORMAL.

## Expected
After the above situation, the mode is NORMAL.
Or when `ddu#start({})` in INSERT mode, the mode is INSERT. when `ddu#start({})` in NORMAL mode , the mode is NORMAL.

## Environment Information

- ddu-ui-ff version (SHA1):
d1bc22e
- denops.vim version (SHA1):
3b489d5
- deno version(`deno -V` output):
deno 1.30.3
- OS:
WSL2 Ubuntu22.04
- neovim/Vim `:version` output:
NVIM v0.9.0-dev-1088+gd66832c76
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({ 'ui': 'ff' })<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	nnoremap <buffer><silent> i
				\ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()

function! s:ddu_filter_my_settings() abort
	inoremap <buffer> <C-q>
				\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f`
2. type `i` for open filter window.
3. type `<C-q>` in filter window in INSERT mode for quit ddu.
4. the mode is INSERT... not NORMAL.

**Comment by Shougo** [comment]
It is intended.  Please see the documentation.

```
Q: When calling |ddu-ui-ff-action-quit| or |ddu-ui-ff-action-itemAction| from
insert mode of the filter window, it remains insert mode.

A: It is the feature.  Because |ddu#ui#do_action()| does not change any mode.
You must escape insert mode when leave from the filter window.
>
	autocmd FileType ddu-ff-filter call s:ddu_ff_filter_my_settings()
	function s:ddu_ff_filter_my_settings() abort
	  inoremap <buffer> <Esc>
	  \ <Esc><Cmd>call ddu#ui#do_action('quit')<CR>
	  inoremap <buffer> <CR>
	  \ <ESC><Cmd>call ddu#ui#do_action('itemAction')<CR>
	endfunction
<
```
