### ISSUE TITLE
preview window's width is not arranged correctly when setting border

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-ff#99]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
preview window's width and main window's width should be same.
Or user can setting preview window's width when setting when setting `previewSplit` is `horizontal`.

## Environment Information

- ddu-ui-ff version (SHA1):
361bc52
- denops.vim version (SHA1):
df65c22
- deno version(`deno -V` output):
deno 1.30.3
- OS:
WSL2 Ubuntu22.04
- neovim/Vim `:version` output:
NVIM v0.9.0-dev-1088+gd66832c76
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file_rec
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\	'ff': {
			\		'startFilter': v:true,
			\		'autoAction': {
			\			'name': 'preview',
			\		},
			\		'split': 'floating',
			\		'filterFloatingPosition': 'bottom',
			\		'previewFloating': v:true,
			\		'floatingBorder': 'rounded',
			\		'previewFloatingBorder': 'rounded',
			\	}
			\ },
			\ 'sources': [{'name': 'file_rec', 'params': {}}],
			\ })<CR>

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f` for start ddu

## Screenshot (if possible)
![image](https://github.com/Shougo/ddu-ui-ff/assets/50443168/8093ed38-9da5-4cc5-90fb-fcfda0bb6bbf)

**Comment by kamecha** [comment]
This may not be related to this issue, but when setting `filterFloatingPosition` is `top` and other setting is same above, the preview window is not arrange correctly I think.

screen shot...
![image](https://github.com/Shougo/ddu-ui-ff/assets/50443168/137f3109-cc24-449d-9068-7e64d594c5e6)

**Comment by Shougo** [comment]
Fixed.
